site_name: Verdant Yang 学习笔记
site_description: 日积月累

pages:
- ['index.md', '主页']

# google_analytics: ['UA-27795084-5', 'mkdocs.org']

theme: readthedocs
repo_url: https://github.com/verdantyang/verdant-docs/